# Generated by Django 4.2.7 on 2024-11-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_orderitem_farmerprofile_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='updated',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='region',
            field=models.CharField(choices=[('bamako', 'Bamako'), ('kayes', 'Kayes'), ('koulikoro', 'Koulikoro'), ('sikasso', 'Sikasso'), ('segou', 'Ségou'), ('mopti', 'Mopti'), ('tombouctou', 'Tombouctou'), ('gao', 'Gao'), ('kidal', 'Kidal')], default='bamako', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='farmers/'),
        ),
    ]
