# Generated by Django 4.2.7 on 2024-11-29 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_remove_order_city_remove_order_mobile_money_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('region', models.CharField(choices=[('bamako', 'Bamako'), ('kayes', 'Kayes'), ('koulikoro', 'Koulikoro'), ('sikasso', 'Sikasso'), ('segou', 'Ségou'), ('mopti', 'Mopti'), ('tombouctou', 'Tombouctou'), ('gao', 'Gao'), ('kidal', 'Kidal')], default='bamako', max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='customers/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
